"""add soft delete fields

Revision ID: 4c114958726b
Revises: 3c4d5e6f7890
Create Date: 2026-03-04 11:45:16.037756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4c114958726b'
down_revision: Union[str, None] = '3c4d5e6f7890'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paymentverificationlog_order_id'), table_name='paymentverificationlog')
    op.drop_index(op.f('ix_paymentverificationlog_razorpay_order_id'), table_name='paymentverificationlog')
    op.drop_index(op.f('ix_paymentverificationlog_razorpay_payment_id'), table_name='paymentverificationlog')
    op.drop_table('paymentverificationlog')
    op.drop_index(op.f('ix_idempotencykey_endpoint'), table_name='idempotencykey')
    op.drop_index(op.f('ix_idempotencykey_idempotency_key'), table_name='idempotencykey')
    op.drop_index(op.f('ix_idempotencykey_user_id'), table_name='idempotencykey')
    op.drop_table('idempotencykey')
    op.add_column('order', sa.Column('paid_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('processing_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('shipped_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('cancelled_at', sa.DateTime(), nullable=True))
    op.add_column('order', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_order_deleted_at'), 'order', ['deleted_at'], unique=False)
    op.add_column('product', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_product_deleted_at'), 'product', ['deleted_at'], unique=False)
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_user_deleted_at'), 'user', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_deleted_at'), table_name='user')
    op.drop_column('user', 'deleted_at')
    op.drop_index(op.f('ix_product_deleted_at'), table_name='product')
    op.drop_column('product', 'deleted_at')
    op.drop_index(op.f('ix_order_deleted_at'), table_name='order')
    op.drop_column('order', 'deleted_at')
    op.drop_column('order', 'cancelled_at')
    op.drop_column('order', 'delivered_at')
    op.drop_column('order', 'shipped_at')
    op.drop_column('order', 'processing_at')
    op.drop_column('order', 'paid_at')
    op.create_table('idempotencykey',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('endpoint', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('request_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_json', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_status_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('idempotencykey_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('idempotencykey_pkey'))
    )
    op.create_index(op.f('ix_idempotencykey_user_id'), 'idempotencykey', ['user_id'], unique=False)
    op.create_index(op.f('ix_idempotencykey_idempotency_key'), 'idempotencykey', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_idempotencykey_endpoint'), 'idempotencykey', ['endpoint'], unique=False)
    op.create_table('paymentverificationlog',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('razorpay_order_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('razorpay_payment_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('razorpay_signature', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('is_valid', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('attempt_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_attempts', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('failed_at', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('verified_by', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name=op.f('paymentverificationlog_order_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('paymentverificationlog_pkey'))
    )
    op.create_index(op.f('ix_paymentverificationlog_razorpay_payment_id'), 'paymentverificationlog', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_paymentverificationlog_razorpay_order_id'), 'paymentverificationlog', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_paymentverificationlog_order_id'), 'paymentverificationlog', ['order_id'], unique=False)
    # ### end Alembic commands ###
