"""Phase 3: inventory reservations, refunds, discounts, shipping, tax, search, stock alerts

Revision ID: f77f4fd5501c
Revises: 4c114958726b
Create Date: 2026-03-06 00:37:24.964884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f77f4fd5501c'
down_revision: Union[str, None] = '4c114958726b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coupon',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('discount_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('uses_per_user', sa.Integer(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('min_order_value', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coupon_code'), 'coupon', ['code'], unique=True)
    op.create_table('customertier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_ltv', sa.Float(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('shippingcountry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_supported', sa.Boolean(), nullable=False),
    sa.Column('customs_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippingcountry_code'), 'shippingcountry', ['code'], unique=True)
    op.create_table('shippingrate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('postal_code_pattern', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shippingrate_country'), 'shippingrate', ['country'], unique=False)
    op.create_table('tax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_country'), 'tax', ['country'], unique=False)
    op.create_table('searchlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_searchlog_query'), 'searchlog', ['query'], unique=False)
    op.create_index(op.f('ix_searchlog_timestamp'), 'searchlog', ['timestamp'], unique=False)
    op.create_table('bulkdiscount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('min_quantity', sa.Integer(), nullable=False),
    sa.Column('discount_percent', sa.Float(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulkdiscount_product_id'), 'bulkdiscount', ['product_id'], unique=False)
    op.create_table('couponusage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupon.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_couponusage_coupon_id'), 'couponusage', ['coupon_id'], unique=False)
    op.create_index(op.f('ix_couponusage_order_id'), 'couponusage', ['order_id'], unique=False)
    op.create_index(op.f('ix_couponusage_user_id'), 'couponusage', ['user_id'], unique=False)
    op.create_table('orderstatushistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('to_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orderstatushistory_order_id'), 'orderstatushistory', ['order_id'], unique=False)
    op.create_index(op.f('ix_orderstatushistory_timestamp'), 'orderstatushistory', ['timestamp'], unique=False)
    op.create_table('refund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('razorpay_refund_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refund_order_id'), 'refund', ['order_id'], unique=False)
    op.create_table('inventorytransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('quantity_after', sa.Integer(), nullable=False),
    sa.Column('reference_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventorytransaction_created_at'), 'inventorytransaction', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventorytransaction_product_id'), 'inventorytransaction', ['product_id'], unique=False)
    op.create_index(op.f('ix_inventorytransaction_variant_id'), 'inventorytransaction', ['variant_id'], unique=False)
    op.create_table('stockalert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('current_stock', sa.Integer(), nullable=False),
    sa.Column('threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockalert_product_id'), 'stockalert', ['product_id'], unique=False)
    op.create_index(op.f('ix_stockalert_variant_id'), 'stockalert', ['variant_id'], unique=False)
    op.create_table('stockreservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['productvariant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockreservation_order_id'), 'stockreservation', ['order_id'], unique=False)
    op.create_index(op.f('ix_stockreservation_variant_id'), 'stockreservation', ['variant_id'], unique=False)
    op.add_column('order', sa.Column('shipping_cost', sa.Float(), nullable=False, server_default='0'))
    op.add_column('order', sa.Column('tax_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('order', sa.Column('discount_amount', sa.Float(), nullable=False, server_default='0'))
    op.add_column('order', sa.Column('shipping_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('tracking_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('productvariant', sa.Column('reserved_quantity', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='regular'))
    op.add_column('user', sa.Column('lifetime_value', sa.Float(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lifetime_value')
    op.drop_column('user', 'tier')
    op.drop_column('productvariant', 'reserved_quantity')
    op.drop_column('order', 'tracking_number')
    op.drop_column('order', 'shipping_provider')
    op.drop_column('order', 'discount_amount')
    op.drop_column('order', 'tax_amount')
    op.drop_column('order', 'shipping_cost')
    op.drop_index(op.f('ix_stockreservation_variant_id'), table_name='stockreservation')
    op.drop_index(op.f('ix_stockreservation_order_id'), table_name='stockreservation')
    op.drop_table('stockreservation')
    op.drop_index(op.f('ix_stockalert_variant_id'), table_name='stockalert')
    op.drop_index(op.f('ix_stockalert_product_id'), table_name='stockalert')
    op.drop_table('stockalert')
    op.drop_index(op.f('ix_inventorytransaction_variant_id'), table_name='inventorytransaction')
    op.drop_index(op.f('ix_inventorytransaction_product_id'), table_name='inventorytransaction')
    op.drop_index(op.f('ix_inventorytransaction_created_at'), table_name='inventorytransaction')
    op.drop_table('inventorytransaction')
    op.drop_index(op.f('ix_refund_order_id'), table_name='refund')
    op.drop_table('refund')
    op.drop_index(op.f('ix_orderstatushistory_timestamp'), table_name='orderstatushistory')
    op.drop_index(op.f('ix_orderstatushistory_order_id'), table_name='orderstatushistory')
    op.drop_table('orderstatushistory')
    op.drop_index(op.f('ix_couponusage_user_id'), table_name='couponusage')
    op.drop_index(op.f('ix_couponusage_order_id'), table_name='couponusage')
    op.drop_index(op.f('ix_couponusage_coupon_id'), table_name='couponusage')
    op.drop_table('couponusage')
    op.drop_index(op.f('ix_bulkdiscount_product_id'), table_name='bulkdiscount')
    op.drop_table('bulkdiscount')
    op.drop_index(op.f('ix_searchlog_timestamp'), table_name='searchlog')
    op.drop_index(op.f('ix_searchlog_query'), table_name='searchlog')
    op.drop_table('searchlog')
    op.drop_index(op.f('ix_tax_country'), table_name='tax')
    op.drop_table('tax')
    op.drop_index(op.f('ix_shippingrate_country'), table_name='shippingrate')
    op.drop_table('shippingrate')
    op.drop_index(op.f('ix_shippingcountry_code'), table_name='shippingcountry')
    op.drop_table('shippingcountry')
    op.drop_table('customertier')
    op.drop_index(op.f('ix_coupon_code'), table_name='coupon')
    op.drop_table('coupon')
    # ### end Alembic commands ###
